import { useState } from 'react';
import Head from 'next/head';
import CardContainer from '../components/CardContainer';
import Hero from '../components/Hero';
import Navbar from '../components/Navbar';
import Portfolio from '../components/Portfolio';
import Services from '../components/Services';
import Footer from '../components/Footer';

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);

  return (
    <div
      className={`h-screen snap-y snap-mandatory overflow-y-scroll ${
        darkMode && 'dark'
      }`}
    >
      <Head>
        <title>Next Tailwind Portfolio</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='img/favicon.ico' />
      </Head>

      <main className='bg-white px-10 md:px-20 lg-px-40 dark:bg-gray-900'>
        <section className='min-h-screen snap-start'>
          <Navbar setDarkMode={setDarkMode} darkMode={darkMode} />
          <Hero />
        </section>
        <section className='flex flex-col items-center justify-center min-h-screen snap-start'>
          <Services />
          <CardContainer />
        </section>
        <section className='flex flex-col items-center justify-center min-h-screen snap-start'>
          <Portfolio />
        </section>
        <section className='snap-end'>
          <Footer />
        </section>
      </main>
    </div>
  );
}
