import Head from 'next/head';
import CardContainer from '../components/CardContainer';
import Hero from '../components/Hero';
import Navbar from '../components/Navbar';
import Services from '../components/Services';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Next Tailwind Portfolio</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='img/favicon.ico' />
      </Head>

      <main className='bg-white px-10'>
        <section className='min-h-screen'>
          <Navbar />
          <Hero />
        </section>
        <section>
          <Services />
          <CardContainer />
        </section>
      </main>
    </div>
  );
}
