import Head from 'next/head';
import Navbar from '../components/Navbar';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Next Tailwind Portfolio</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='img/favicon.ico' />
      </Head>

      <main className='bg-white px-10'>
        <section className='min-h-screen'>
          <Navbar />
        </section>
      </main>
    </div>
  );
}
